name: Publish test

on:
  push:
    branches:
      - test

jobs:
  publish:
    if: true
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Use NodeJS 16'
        uses: actions/setup-node@v2
        with:
          node-version: '16.18.1'

      - name: 'Setup lerna@6.6.1'
        run: yarn global add lerna@6.6.1 --ignore-engines

      - name: Build dependencies
        run: |
          node etc/bootstrapEnv
          yarn install --ignore-engines
          yarn build

      - name: 'Commit ibcTokenMetadata.json if changed'
        run: |
          git diff --exit-code -- packages/sdk-ui-ts/src/services/ibc/ibcTokenMetadata.json || git add packages/sdk-ui-ts/src/services/ibc/ibcTokenMetadata.json
          git diff --cached --exit-code || git commit -m "Automatically update ibcTokenMetadata.json"
        continue-on-error: true

      - name: 'Setup npm'
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Version and publish (Dry Run)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          lerna version prerelease --preid beta --force-git-tag --no-changelog --yes --no-git-tag-version --no-push
          lerna publish from-git --force-git-tag --dist-tag next --yes --summary-file --dry-run

      # - name: 'Broadcast published versions on Slack'
      #   run: node etc/slack --api=$SLACK_API --actor=$GIT_ACTOR --commit-message=$GIT_LATEST_COMMIT_MESSAGE
      #   env:
      #     GIT_ACTOR: ${{ github.actor }}
      #     SLACK_API: ${{ secrets.SLACK_API }}
      #     GIT_LATEST_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
